sudo: required
dist: bionic

language: node_js
node_js:
  - 11

addons:
  apt:
    sources:
      -  	https://apache.bintray.com/couchdb-deb
    packages:
      - couchdb

before_install:
  - sudo apt-get install -y couchdb
  - sudo service couchdb restart

before_script:
  - while [ '200' != $(curl -s -o /dev/null -w %{http_code} http://127.0.0.1:5984) ]; do echo waiting for couch to load... ; sleep 1; done  # wait for CouchDB
  - cd "$TRAVIS_BUILD_DIR/todo" && npm install

script:
  - cd "$TRAVIS_BUILD_DIR/todo" && npm test
