dist: bionic

language: node_js
node_js:
  - 11

services:
  - couchdb

before_script:
  - curl -X PUT localhost:5984/myapp_test  # check CouchDB
  - cd "$TRAVIS_BUILD_DIR/todo" && npm install

script:
  - cd "$TRAVIS_BUILD_DIR/todo" && npm test
