dist: bionic

language: node_js
node_js:
  - 11

services:
  - couchdb

before_script:
  - sleep 15  # wait for CouchDB
  - curl http://localhost:5984/  # check CouchDB
  - cd "$TRAVIS_BUILD_DIR/todo" && npm install

script:
  - cd "$TRAVIS_BUILD_DIR/todo" && npm test
