sudo: required
dist: bionic

language: node_js
node_js:
  - 11

services:
  - couchdb


before_script:
  - while [ '200' != $(curl -s -o /dev/null -w %{http_code} http://127.0.0.1:5984) ]; do echo waiting for couch to load... ; sleep 1; done # wait for CouchDB
  - curl -X PUT http://127.0.0.1:5984/_users
  - curl -X PUT http://127.0.0.1:5984/_replicator
  - curl -X PUT http://127.0.0.1:5984/_global_changes
  - curl http://127.0.0.1:5984/_config/vendor/version
  - cd "$TRAVIS_BUILD_DIR/todo" && npm install

script:
  - cd "$TRAVIS_BUILD_DIR/todo" && npm test
